# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e453c3ceed648764774b375e2aeb0282527109659e83b66be6298802bdfd68a0c8359c541006b48bb1fdd7d21fae78b9907763abc5642b3ccef152da4bcaca26

test:
  secret_key_base: dd12a8adcd3e702b15fc831f51f7d5e3870d9b0962d4d2d5ea08a00f688c628643a4fbb7e21374a1152029b653fc3956517d9ad9dbca941bbcf1d2c77d6e40a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
